sudo: required
dist: trusty
group: edge
services: docker
language: python
python: '3.6'
cache: pip
before_install:
    - pip install Fabric3
script: docker-compose run django py.test
after_success: docker-compose down && fab deploy
