version: '2'

volumes:
  django-static:
  django-media:


services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
      args:
          DJANGO_ENV: production
    depends_on:
      - postgres
      - redis
    env_file: .env
    command: /gunicorn.sh

  postgres:
    image: postgres:9.6
    env_file: .env

  caddy:
    image: abiosoft/caddy
    depends_on:
      - django
    volumes:
      - ./compose/caddy/Caddyfile:/etc/Caddyfile:ro  # configuration
      - ./staticfiles:/app/staticfiles:ro  # serving django's statics
      - ./media:/app/media:ro  # serving django's media
    ports:
      - '80:80'
      - '443:443'

  redis:
    image: redis:3.0

  vue:
    build:
      context: .
      dockerfile: ./compose/vue/Dockerfile
    command: npm run build
    volumes:
      - .:/app
      - /app/node_modules
    env_file: .env
