version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}


services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER={{cookiecutter.project_slug}}


  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    restart: always
    depends_on:
      - postgres
      {% if cookiecutter.use_mailhog == 'y' -%}
      - mailhog
      {% endif %}
    environment:
      - POSTGRES_USER={{cookiecutter.project_slug}}
    volumes:
      - .:/app
    ports:
      - "8000:8000"


  webpack:
    build:
      context: .
      dockerfile: ./compose/webpack/Dockerfile
    command: npm run dev
    restart: always
    volumes_from:
      - django
    ports:
      - "3000:3000"


  {% if cookiecutter.use_mailhog == 'y' -%}
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"{% endif %}
